from typing import List

ABBREVIATIONS: List[str] = ["sec.",
                            "secs.",
                            "Sec.",
                            "Secs.",
                            "fig.",
                            "figs.",
                            "Fig.",
                            "Figs.",
                            "FIG.",
                            "FIGS.",
                            "Pat.",
                            "eq.",
                            "eqs.",
                            "Eq.",
                            "Eqs.",
                            "no.",
                            "nos.",
                            "No.",
                            "Nos.",
                            "al."]
